# Project information
site_name: 机械组入门手册-千里MechaX
site_url: https://ostoponko.github.io/docmech/
site_author: Ostoponko

# Repository
repo_name: ostoponko/docmech
repo_url: https://github.com/ostoponko/docmech

# Copyright
copyright: Copyright &copy; 2023 - 2024 Ostoponko

# Configuration
theme:
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - toc.integrate
    - navigation.footer

  logo: 'pic/favicon1.jpg'
  favicon: 'pic/favicon1.ico'
  name: 'material'
  palette:
    primary: black
    accent: indigo

# Customization
extra:
  social:
    - icon: fontawesome/solid/school
      link: https://sxic.cqu.edu.cn/home
      name: 交叉创新中心
    - icon: fontawesome/brands/github
      link: https://github.com/CQUMechaX
      name: 千里MechaX战队-Github
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1432987899
      name: 千里MechaX-B站
    - icon: fontawesome/solid/book
      link: https://mechax.readthedocs.io/zh_CN/latest/
      name: 战队文档主站

  consent:
    title: Cookie consent
    description: >- 
      我们使用cookie来识别您的重复访问和偏好，并衡量我们文档的有效性以及用户是否找到了他们正在搜索的内容。在您的同意下，您正在帮助我们改进文档。

# Extensions
markdown_extensions:
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Page tree
nav:
  - 主页 Home:
     - 欢迎: index.md
     - 写在前面: Preface.md
     - 版本说明: version.md
     - 参考目录: contents.md
     - 使用时的问题:
         - 无法加载图片: prob1.md
         - 问题反馈: prob2.md

  - 引入章节 Intro:

      - 0 内容概述:
          - 0.1 手册的编写逻辑: Chapter1/编写逻辑.md
          - 0.2 机械组成员的工作范围: Chapter1/工作范围.md
          - 0.3 机械组成员需要的能力素养: Chapter1/能力与素养.md
          - 0.4 如何学习与实践: Chapter1/学习与实践.md

      - 1 引入章节：初识机器人与机电系统:
          - 1.1 何为机器人:
              - 1.1.1 机器人的定义: Chapter2/何为机器人.md
              - 1.1.2 机器人的组成: Chapter2/机器人组成.md
              - 1.1.3 机器人的历史与未来: Chapter2/机器人发展.md
          - 1.2 常见的机器人:
              - 1.2.1 轮式机器人: Chapter2/轮式机器人.md
              - 1.2.2 机械臂: Chapter2/机械臂.md
              - 1.2.3 仿生机器人：四足与人形: Chapter2/仿生机器人.md
              - 1.2.4 轮足机器人: Chapter2/轮足机器人.md
              - 1.2.5 其他有趣的机器人: Chapter2/robots.md
          - 1.3 认识常见的机电系统:
              - 1.3.1 电动螺丝刀: Chapter2/电动螺丝刀.md
              - 1.3.2 3D打印机和雕刻机: Chapter2/3D打印机和雕刻机.md

      - 2 引入章节：初入RM:
          - 2.1 Robomaster比赛机制: Chapter0/比赛机制.md
          - 2.2 初识RM机器人兵种:
              - 2.2.1 地面射击兵种: Chapter0/地面射击兵种.md
              - 2.2.2 工程机器人: Chapter0/工程机器人.md
              - 2.2.3 飞镖: Chapter0/飞镖.md
              - 2.2.4 无人机: Chapter0/无人机.md
          - 2.3 赛季规划与RM生涯规划: Chapter0/RM规划.md


  - 实践章节 Practice:

      - 4 实践章节1：Lab Tour1：工具的使用与结构拆装:
          - 4.1 常见工具的使用:
              - 4.1.1 工具简介: Chapter4/工具简介.md
              - 4.1.2 加工相关: Chapter4/加工相关.md
              - 4.1.3 拆装相关: Chapter4/拆装相关.md
              - 4.1.4 测量相关: Chapter4/测量相关.md
          - 4.2 机械结构拆装:
              - 4.2.1 步兵轮组拆装: Chapter4/步兵轮组拆装.md
              - 4.2.2 步兵云台拆装: Chapter4/步兵云台拆装.md

      - 5 实践章节2：零件建模与机械制图:
          - 5.1 建模软件及其基本设置:
              - 5.1.1 建模：Solidworks: Chapter5/Solidworks及其设置.md
              - 5.1.2 建模：Fusion: Chapter5/Fusion 360及其设置.md
              - 5.1.3 建模步骤与思路: Chapter5/建模步骤与思路.md
          - 5.2 常规零件建模以及简单装配体:
              - 5.2.1 示例1：悬臂板的绘制: Chapter5/悬臂板的绘制.md
              - 5.2.2 示例2：法兰联轴器的绘制: Chapter5/法兰联轴器的绘制.md
              - 5.2.3 示例3：抱紧式联轴器的绘制: Chapter5/抱紧式联轴器的绘制.md
              - 5.2.4 示例4：3D打印台钳的绘制: Chapter5/3D打印台钳的绘制.md
          - 5.3 加工图纸以及外发加工注意事项:
              - 5.3.1 尺寸标注与尺寸公差: Chapter5/尺寸标注与尺寸公差.md
              - 5.3.2 形位公差: Chapter5/形位公差.md
              - 5.3.3 制图技术要求: Chapter5/技术要求.md
              - 5.3.4 外发加工注意事项: Chapter5/外发加工注意事项.md

      - 7 实践章节3：装配体建模:
          - 7.1 软件中的装配操作:
              - 7.1.1 装配操作：SW: Chapter7/SW装配.md
              - 7.1.2 装配操作：Fusion: Chapter7/Fusion装配.md
          - 7.2 自顶向下的装配体布局: Chapter7/装配体示例.md
          - 7.3 Misumi Rapid Designer的使用: Chapter7/标准件导入.md

      - 9 实践章节4：连杆机构的设计:
          - 9.1 开源连杆机构仿真软件Pyslvs:
              - 9.1.1 基本操作: Chapter9/Pyslvs基本操作.md
              - 9.1.2 软件示例: Chapter9/Pyslvs示例.md
          - 9.2 设计实例：瓦特连杆: Chapter9/watt_linkage.md
          - 9.3 设计实例：连杆参数优化: Chapter9/连杆参数优化.md
          - 9.4 RM设计中的连杆机构: Chapter9/RM连杆机构.md

      - 11 实践章节5：3D打印实操:
          - 11.1 切片软件：Superslicer: Chapter11/Superslicer.md
          - 11.2 切片操作与打印: Chapter11/切片操作与打印.md
          - 11.3 打印常见问题与解决方案: Chapter11/打印常见问题与解决方案.md
          - 11.4 调机指南: Chapter11/调机指南.md

      - 15 实践章节6：带传动设计与平移机构设计:
          - 15.1 闭口与开口同步带:
              - 15.1.1 闭口同步带设计插件使用: Chapter15/闭口同步带设计插件使用.md
              - 15.1.2 开口同步带的固定方式: Chapter15/开口同步带的固定方式.md
          - 15.2 张紧机构设计:
              - 15.2.1 惰轮张紧: Chapter15/惰轮张紧.md
          - 15.3 同步带设计案例:
              - 15.3.1 KUKA机器人的5、6轴传动: Chapter15/KUKA.md
              - 15.3.2 同步带横移机构: Chapter15/同步带横移机构.md
              - 15.3.3 23赛季4号步兵: Chapter15/4号步兵.md

  - 理论章节 Theory:
      - 6 理论章节1：理论力学:
          - 6.1 静力学:
              - 6.1.1 平面力系: Chapter6/平面力系.md
              - 6.1.2 摩擦: Chapter6/摩擦.md
          - 6.2 运动学:
              - 6.2.1 点的运动: Chapter6/点的运动.md
              - 6.2.2 刚体运动: Chapter6/刚体运动.md
          - 6.3 动力学:
              - 6.3.1 动量定理: Chapter6/动量定理.md
              - 6.3.2 动量矩定理: Chapter6/动量矩定理.md
              - 6.3.3 动能定理: Chapter6/动能定理.md
              - 6.3.4 达朗贝尔原理: Chapter6/达朗贝尔原理.md
              - 6.3.5 虚位移原理: Chapter6/虚位移原理.md

      - 8 理论章节2：机械原理:
          - 8.1 运动副与结构简图:
              - 8.1.1 运动副: Chapter8/运动副.md
              - 8.1.2 结构简图的绘制: Chapter8/结构简图的绘制.md
          - 8.2 运动分析和力分析:
              - 8.2.1 运动分析: Chapter8/运动分析.md
              - 8.2.2 力分析: Chapter8/力分析.md
          - 8.3 连杆机构:
              - 8.3.1 连杆机构传动特点: Chapter8/连杆机构传动特点.md
              - 8.3.2 连杆机构分析: Chapter8/连杆机构分析.md
              - 8.3.3 连杆设计综合: Chapter8/连杆设计综合.md
          - 8.4 凸轮机构:
              - 8.4.1 凸轮机构分析: Chapter8/凸轮机构分析.md
              - 8.4.2 凸轮机构反求设计: Chapter8/凸轮机构反求设计.md
          - 8.5 齿轮机构:
              - 8.5.1 渐开线标准圆柱齿轮: Chapter8/渐开线标准圆柱齿轮.md
              - 8.5.2 啮合传动: Chapter8/啮合传动.md
              - 8.5.3 切制原理: Chapter8/切制原理.md
              - 8.5.4 其他齿轮传动: Chapter8/其他齿轮传动.md
          - 8.6 齿轮轮系:
              - 8.6.1 定轴轮系与周转轮系: Chapter8/定轴轮系与周转轮系.md
              - 8.6.2 复合轮系: Chapter8/复合轮系.md
          - 8.7 其他常用机构:
              - 8.7.1 间歇机构: Chapter8/棘轮机构与槽轮机构.md
              - 8.7.2 不完全齿轮机构: Chapter8/不完全齿轮机构.md
              - 8.7.3 带有挠性元件的传动机构: Chapter8/带有挠性元件的传动机构.md

      - 12 理论章节3：材料力学与工程材料:
          - 12.1 材料力学基本概念: Chapter12/cllx1.md
          - 12.2 杆件拉压与材料的力学性能: Chapter12/cllx2.md
          - 12.3 有关应力的其他概念: Chapter12/cllx3.md
          - 12.4 剪切与扭转: Chapter12/cllx4.md
          - 12.5 弯曲: Chapter12/cllx5.md
          - 12.6 应力应变理论: Chapter12/cllx6.md
          - 12.7 压杆稳定: Chapter12/cllx7.md

      - 18 理论章节5：机械设计之轴承与轴系:
          - 18.1 轴承:
               - 18.1.1 滚动轴承: Chapter18/滚动轴承.md
               - 18.1.2 滑动轴承: Chapter18/滑动轴承.md
          - 18.2 轴与轴系:
               - 18.2.1 轴: Chapter18/轴.md
               - 18.2.2 轴系设计: Chapter18/轴系设计.md


      - 27 理论章节7：控制理论基础:
          - 27.1 动态系统的建模:
               - 27.1.1 动态系统与微分方程: Chapter27/动态系统与微分方程.md
               - 27.1.2 拉普拉斯变换及逆变换: Chapter27/拉普拉斯变换及逆变换.md
               - 27.1.3 控制框图与传递函数: Chapter27/控制框图与传递函数.md
               - 27.1.4 一阶系统的单位阶跃响应: Chapter27/一阶系统的单位阶跃响应.md
               - 27.1.5 二阶系统（弹簧-质量-阻尼系统）: Chapter27/二阶系统（弹簧-质量-阻尼系统）.md
               - 27.1.6 频率响应: Chapter27/频率响应.md
               - 27.1.7 伯德图: Chapter27/伯德图.md
          - 27.2 自动控制原理之经典控制理论:
               - 27.2.1 闭环系统: Chapter27/闭环系统.md
               - 27.2.2 稳定性分析: Chapter27/稳定性分析.md
               - 27.2.3 终值定理与稳态误差: Chapter27/终值定理与稳态误差.md
               - 27.2.4 PI控制: Chapter27/PI控制.md
               - 27.2.5 根轨迹: Chapter27/根轨迹.md
               - 27.2.6 超前与滞后补偿: Chapter27/超前与滞后补偿.md
               - 27.2.7 PID控制器: Chapter27/PID控制器.md

  - 专题学习 Topic:
      - 3 专题学习1：机器人的构成:
          - 3.1 静态结构:
              - 3.1.1 结构框架: Chapter3/结构框架.md
              - 3.1.2 紧固件: Chapter3/紧固件.md
          - 3.2 执行部件: Chapter3/执行部件.md
          - 3.3 传动部件:
              - 3.3.1 齿轮传动: Chapter3/齿轮传动.md
              - 3.3.2 带传动: Chapter3/带传动.md
              - 3.3.3 连杆传动: Chapter3/连杆传动.md
          - 3.4 动力部件:
              - 3.4.1 电机及其分类: Chapter3/电机及其分类.md
              - 3.4.2 无刷电机及驱动: Chapter3/无刷电机及驱动.md
              - 3.4.3 RM官方电机: Chapter3/RM官方电机.md
          - 3.5 硬件电路: 硬件系统.md
          - 3.6 视觉系统: 视觉系统.md
          - 3.7 裁判系统: 裁判系统.md

      - 10 专题学习2：3D打印技术（FDM）:
          - 10.1 认识3D打印机：基本组成:
              - 10.1.1 结构部件: Chapter10/结构部件.md
              - 10.1.2 驱动与传动部件: Chapter10/驱动与传动部件.md
              - 10.1.3 核心工作部件：挤出机与喷头: Chapter10/核心工作部件挤出机与喷头.md
              - 10.1.4 传感器：开关与热敏电阻: Chapter10/传感器开关与热敏电阻.md
          - 10.2 常见的3D打印机设备构型及其特点:
              - 10.2.1 MB与UM2结构: Chapter10/MB与UM2结构.md
              - 10.2.2 I3与悬臂结构: Chapter10/I3与悬臂结构.md
              - 10.2.3 Delta三角洲并联结构: Chapter10/Delta三角洲并联结构.md
              - 10.2.4 coreXY结构: Chapter10/coreXY结构.md
              - 10.2.5 极坐标结构与五轴打印: Chapter10/极坐标结构与五轴打印.md
          - 10.3 FDM打印的常用材料:
              - 10.3.1 PLA（聚乳酸）: Chapter10/PLA聚乳酸.md
              - 10.3.2 ABS（丙烯腈丁二烯苯乙烯）: Chapter10/ABS.md
              - 10.3.3 PETG（聚对苯二甲酸乙二醇酯）: Chapter10/PETG.md
              - 10.3.4 TPU（热塑性聚氨酯）: Chapter10/TPU.md
              - 10.3.5 复合材料（纤维增强）: Chapter10/复合材料.md

      - 17 专题学习4：3D打印机结构设计:
          - 17.1 经典案例：Voron2.4:
              - 17.1.1 coreXY同步带传动路径: Chapter17/coreXY同步带传动路径.md
              - 17.1.2 Z轴设计: Chapter17/Z轴设计.md
              - 17.1.3 热端设计: Chapter17/热端设计.md

      - 19 专题学习5：认识减速器:
          - 19.1 行星减速器: Chapter19/行星减速器.md
          - 19.2 摆线针轮减速器: Chapter19/摆线针轮减速器.md
          - 19.3 谐波减速器: Chapter19/谐波减速器.md
          - 19.4 其他新型减速器: Chapter19/其他新型减速器.md



  - 手册参考 Reference: Reference.md
  - 关于 About: About.md
  - 相关链接 Links: Links.md