site_name: MechaX-机械组入门手册

theme:
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - toc.integrate
  logo: 'pic/tools.svg'
  favicon: 'pic/tools.svg'
  name: 'material'
  palette:
    primary: indigo
    accent: red

nav:
  - 主页 Home:
     - 主页: index.md
     - 写在前面: Preface.md

  - 引入章节 Intro:

      - 1 内容概述:
          - 1.1 手册的编写逻辑: Chapter1\编写逻辑.md
          - 1.2 机械组成员的工作范围: Chapter1\工作范围.md
          - 1.3 机械组成员需要的能力素养: Chapter1\能力与素养.md
          - 1.4 如何学习与实践: Chapter1\学习与实践.md

      - 2 引入章节：初识机器人与RM:
          - 2.1 何为机器人:
              - 2.1.1 轮式机器人: Chapter2\轮式机器人.md
              - 2.1.2 机械臂: Chapter2\机械臂.md
              - 2.1.3 轮足机器人: Chapter2\轮足机器人.md
              - 2.1.4 仿生机器人：四足与人形: Chapter2\仿生机器人.md
          - 2.2 RM比赛机制: Chapter2\比赛机制.md
          - 2.3 初识RM机器人兵种:
              - 2.3.1 地面射击兵种: Chapter2\地面射击兵种.md
              - 2.3.2 工程机器人: Chapter2\工程机器人.md
              - 2.3.3 飞镖: Chapter2\飞镖.md
              - 2.3.4 无人机: Chapter2\无人机.md
          - 2.4 认识常见的机电系统:
              - 2.4.1 电动螺丝刀: Chapter2\电动螺丝刀.md
              - 2.4.2 3D打印机和雕刻机: Chapter2\3D打印机和雕刻机.md

  - 实践章节 Practice:

      - 4 实践章节1：工具的使用与机械结构拆装:
          - 4.1 工具、刀具与量具:
              - 4.1.1 工具简介: Chapter4\工具简介.md
              - 4.1.1 钳工必备：台钳与锉刀: Chapter4\台钳与锉刀.md
              - 4.1.2 3D打印后处理：倒角刀与砂纸: Chapter4\倒角刀与砂纸.md
              - 4.1.3 如何打螺丝：螺丝刀与批头: Chapter4\螺丝刀与批头.md
              - 4.1.4 电钻与冲击钻: Chapter4\电钻与冲击钻.md
              - 4.1.5 丝锥与攻丝机: Chapter4\丝锥与攻丝机.md
              - 4.1.6 游标卡尺与高度尺: Chapter4\游标卡尺与高度尺.md
              - 4.1.7 其他测量仪器: Chapter4\其他测量仪器.md
          - 4.2 机械结构拆装:
              - 4.2.1 步兵轮组拆装: Chapter4\步兵轮组拆装.md
              - 4.2.2 步兵云台拆装: Chapter4\步兵云台拆装.md

      - 5 实践章节2：零件建模与机械制图:
          - 5.1 建模软件及其基本设置:
              - 5.1.1 Solidworks及其设置: Chapter5\Solidworks及其设置.md
              - 5.1.2 Fusion 360及其设置: Chapter5\Fusion 360及其设置.md
              - 5.1.3 草图、特征以及实体: Chapter5\草图特征以及实体.md
          - 5.2 常规零件建模以及简单装配体:
              - 5.2.1 示例1：悬臂板的绘制（草图定义及拉伸实体）: Chapter5\悬臂板的绘制.md
              - 5.2.2 示例2：法兰联轴器的绘制（回转体及圆周阵列）: Chapter5\法兰联轴器的绘制.md
              - 5.2.3 示例3：抱紧式联轴器的绘制（定义平面）: Chapter5\抱紧式联轴器的绘制.md
              - 5.2.4 示例4：3D打印台钳的绘制（螺纹以及装配体）: Chapter5\3D打印台钳的绘制.md
          - 5.3 加工图纸以及外发加工注意事项:
              - 5.3.1 制图：尺寸标注与尺寸公差: Chapter5\尺寸标注与尺寸公差.md
              - 5.3.2 制图：形位公差: Chapter5\形位公差.md
              - 5.3.3 制图：技术要求: Chapter5\技术要求.md
              - 5.3.4 外发加工注意事项: Chapter5\外发加工注意事项.md

      - 9.实践章节4：连杆机构的设计:
          - 9.1 开源连杆机构仿真软件Pyslvs:
              - 9.1.1 基本操作: Chapter9\Pyslvs基本操作.md
              - 9.1.2 仿真输出: Chapter9\Pyslvs仿真输出.md
              - 9.1.3 软件示例: Chapter9\Pyslvs示例.md
          - 9.2 设计实例：瓦特连杆: Chapter9\watt_linkage.md
          - 9.3 设计实例：连杆参数优化: Chapter9\连杆参数优化.md
          - 9.4 RM设计中的连杆机构: Chapter9\RM连杆机构.md

      - 11 实践章节5：3D打印实操:
          - 11.1 切片软件：Superslicer: Chapter11\Superslicer.md
          - 11.2 切片操作与打印: Chapter11\切片操作与打印.md
          - 11.3 打印常见问题与解决方案: Chapter11\打印常见问题与解决方案.md
          - 11.4 调机指南: Chapter11\调机指南.md

      - 15 实践章节6：带传动设计与平移机构设计:
          - 15.1 闭口与开口同步带:
              - 15.1.1 闭口同步带设计插件使用: Chapter15\闭口同步带设计插件使用.md
              - 15.1.2 开口同步带的固定方式: Chapter15\开口同步带的固定方式.md
          - 15.2 张紧机构设计:
              - 15.2.1 惰轮张紧: Chapter15\惰轮张紧.md
          - 15.3 同步带设计案例:
              - 15.3.1 KUKA机器人的5、6轴传动: Chapter15\KUKA.md
              - 15.3.2 同步带横移机构: Chapter15\同步带横移机构.md
              - 15.3.3 23赛季4号步兵: Chapter15\4号步兵.md


  - 理论章节 Theory:
      - 6 理论章节1：理论力学:
          - 6.1 静力学:
              - 6.1.1 平面力系: Chapter6\平面力系.md
              - 6.1.2 空间力系: Chapter6\空间力系.md
              - 6.1.3 摩擦: Chapter6\摩擦.md
          - 6.2 运动学:
              - 6.2.1 点的运动: Chapter6\点的运动.md
              - 6.2.2 刚体运动: Chapter6\刚体运动.md
          - 6.3 动力学:
              - 6.3.1 动量定理: Chapter6\动量定理.md
              - 6.3.2 动量矩定理: Chapter6\动量矩定理.md
              - 6.3.3 动能定理: Chapter6\动能定理.md
              - 6.3.4 达朗贝尔原理: Chapter6\达朗贝尔原理.md
              - 6.3.5 虚位移原理: Chapter6\虚位移原理.md

      - 8 理论章节2：机械原理:
          - 8.1 运动副与结构简图:
              - 8.1.1 运动副: Chapter8\运动副.md
              - 8.1.2 结构简图的绘制: Chapter8\结构简图的绘制.md
          - 8.2 运动分析和力分析:
              - 8.2.1 运动分析: Chapter8\运动分析.md
              - 8.2.2 力分析: Chapter8\力分析.md
          - 8.3 连杆机构:
              - 8.3.1 连杆机构传动特点: Chapter8\连杆机构传动特点.md
              - 8.3.2 连杆机构分析: Chapter8\连杆机构分析.md
              - 8.3.3 连杆设计综合: Chapter8\连杆设计综合.md
          - 8.4 凸轮机构:
              - 8.4.1 凸轮机构分析: Chapter8\凸轮机构分析.md
              - 8.4.2 凸轮机构反求设计: Chapter8\凸轮机构反求设计.md
          - 8.5 齿轮机构:
              - 8.5.1 渐开线标准圆柱齿轮: Chapter8\渐开线标准圆柱齿轮.md
              - 8.5.2 啮合传动: Chapter8\啮合传动.md
              - 8.5.3 切制原理: Chapter8\切制原理.md
              - 8.5.4 其他齿轮传动: Chapter8\其他齿轮传动.md
          - 8.6 齿轮轮系:
              - 8.6.1 定轴轮系与周转轮系: Chapter8\定轴轮系与周转轮系.md
              - 8.6.2 复合轮系: Chapter8\复合轮系.md
          - 8.7 其他常用机构:
              - 8.7.1 棘轮机构与槽轮机构: Chapter8\棘轮机构与槽轮机构.md
              - 8.7.2 凸轮间歇机构: Chapter8\凸轮间歇机构.md
              - 8.7.3 不完全齿轮机构: Chapter8\不完全齿轮机构.md
              - 8.7.4 带有挠性元件的传动机构: Chapter8\带有挠性元件的传动机构.md

      - 18 理论章节5：机械设计之轴承与轴系:
          - 18.1 轴承:
               - 18.1.1 滚动轴承: Chapter18\滚动轴承.md
               - 18.1.2 滑动轴承: Chapter18\滑动轴承.md
          - 18.2 轴与轴系:
               - 18.2.1 轴: Chapter18\轴.md
               - 18.2.2 轴系设计: Chapter18\轴系设计.md


      - 27 理论章节7：控制理论基础:
          - 27.1 动态系统的建模:
               - 27.1.1 动态系统与微分方程: Chapter27\动态系统与微分方程.md
               - 27.1.2 拉普拉斯变换及逆变换: Chapter27\拉普拉斯变换及逆变换.md
               - 27.1.3 控制框图与传递函数: Chapter27\控制框图与传递函数.md
               - 27.1.4 一阶系统的单位阶跃响应: Chapter27\一阶系统的单位阶跃响应.md
               - 27.1.5 二阶系统（弹簧-质量-阻尼系统）: Chapter27\二阶系统（弹簧-质量-阻尼系统）.md
               - 27.1.6 频率响应: Chapter27\频率响应.md
               - 27.1.7 伯德图: Chapter27\伯德图.md
          - 27.2 自动控制原理之经典控制理论:
               - 27.2.1 闭环系统: Chapter27\闭环系统.md
               - 27.2.2 稳定性分析: Chapter27\稳定性分析.md
               - 27.2.3 终值定理与稳态误差: Chapter27\终值定理与稳态误差.md
               - 27.2.4 PI控制: Chapter27\PI控制.md
               - 27.2.5 根轨迹: Chapter27\根轨迹.md
               - 27.2.6 超前与滞后补偿: Chapter27\超前与滞后补偿.md
               - 27.2.7 PID控制器: Chapter27\PID控制器.md

  - 专题学习 Topic:
      - 3 专题学习1：机器人的构成:
          - 3.1 静态结构:
              - 3.1.1 结构框架: Chapter3\结构框架.md
              - 3.1.2 紧固件: Chapter3\紧固件.md
          - 3.2 执行部件:
              - 3.2.1 轮式机器人的各种轮子: Chapter3\轮式机器人的各种轮子.md
              - 3.2.2 机械臂末端夹爪/吸盘: Chapter3\机械臂末端执行器.md
          - 3.3 传动部件:
              - 3.3.1 齿轮传动: Chapter3\齿轮传动.md
              - 3.3.2 带传动: Chapter3\带传动.md
              - 3.3.3 连杆传动: Chapter3\连杆传动.md
          - 3.4 动力部件:
              - 3.4.1 电机及其分类: Chapter3\电机及其分类.md
              - 3.4.2 无刷电机及驱动: Chapter3\无刷电机及驱动.md
              - 3.4.3 RM官方电机: Chapter3\RM官方电机.md
          - 3.5 电控系统:
              - 3.5.1 电池: Chapter3\电池.md
              - 3.5.2 主控板: Chapter3\主控板.md
              - 3.5.3 遥控器与接收机: Chapter3\遥控器与接收机.md
          - 3.6 视觉系统:
              - 3.6.1 工业相机: Chapter3\工业相机.md
              - 3.6.2 miniPC: Chapter3\miniPC.md
          - 3.7 裁判系统:
              - 3.7.1 装甲板: Chapter3\装甲板.md
              - 3.7.2 主控和电源管理: Chapter3\主控和电源管理.md
              - 3.7.3 图传系统: Chapter3\图传系统.md
              - 3.7.4 其他: Chapter3\其他.md

      - 10 专题学习2：3D打印技术（FDM）:
          - 10.1 认识3D打印机：基本组成:
              - 10.1.1 结构部件: Chapter10\结构部件.md
              - 10.1.2 驱动与传动部件: Chapter10\驱动与传动部件.md
              - 10.1.3 核心工作部件：挤出机与喷头: Chapter10\核心工作部件挤出机与喷头.md
              - 10.1.4 传感器：开关与热敏电阻: Chapter10\传感器开关与热敏电阻.md
          - 10.2 常见的3D打印机设备构型及其特点:
              - 10.2.1 MB与UM2结构: Chapter10\MB与UM2结构.md
              - 10.2.2 I3与悬臂结构: Chapter10\I3与悬臂结构.md
              - 10.2.3 Delta三角洲并联结构: Chapter10\Delta三角洲并联结构.md
              - 10.2.4 coreXY结构: Chapter10\coreXY结构.md
              - 10.2.5 极坐标结构与五轴打印: Chapter10\极坐标结构与五轴打印.md
          - 10.3 FDM打印的常用材料:
              - 10.3.1 PLA（聚乳酸）: Chapter10\PLA聚乳酸.md
              - 10.3.2 ABS（丙烯腈丁二烯苯乙烯）: Chapter10\ABS.md
              - 10.3.3 PETG（聚对苯二甲酸乙二醇酯）: Chapter10\PETG.md
              - 10.3.4 TPU（热塑性聚氨酯）: Chapter10\TPU.md
              - 10.3.5 复合材料（纤维增强）: Chapter10\复合材料.md

      - 17 专题学习4：3D打印机结构设计:
          - 17.1 经典案例：Voron2.4:
              - 17.1.1 coreXY同步带传动路径: Chapter17\coreXY同步带传动路径.md
              - 17.1.2 Z轴设计: Chapter17\Z轴设计.md
              - 17.1.3 热端设计: Chapter17\热端设计.md

      - 19 专题学习5：认识减速器:
          - 19.1 行星减速器: Chapter19\行星减速器.md
          - 19.2 摆线针轮减速器: Chapter19\摆线针轮减速器.md
          - 19.3 谐波减速器: Chapter19\谐波减速器.md
          - 19.4 其他新型减速器: Chapter19\其他新型减速器.md



  - 手册参考 Reference: Reference.md
  - 关于 About: About.md
  - 相关链接 Links: Links.md